version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eventsProject
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - events-network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8087:8081"
    volumes:
      - nexus-data:/nexus-data
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g"
    restart: always
    networks:
      - events-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9001:9000" #http://localhost:9001
    depends_on:
      - nexus
    restart: always
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - events-network

  events-app:
    image: radhouene101/devops-validation:84
    container_name: events-app
    ports:
      - "8090:8089"
    depends_on:
      - mysql
      - sonarqube
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/eventsProject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
    networks:
      - events-network

  # Jenkins is already running externally, so we'll include its existing host as part of the network
  jenkins-external:
    image: alpine
    container_name: jenkins-external
    networks:
      - events-network
    command: tail -f /dev/null

volumes:
  mysql_data:
    driver: local
  nexus-data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local

networks:
  events-network:
    driver: bridge
