version: "3.8"

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8088:8081" # Nexus will be accessible at http://localhost:8081
    volumes:
      - nexus-data:/nexus-data # Persists Nexus data
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms1200m -Xmx1200m -XX:MaxDirectMemorySize=2g" # JVM tuning
    restart: always

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000" # SonarQube will be accessible at http://localhost:9000
    depends_on:
      - nexus
    restart: always
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

  events-app:
    image: radhouene101/devops-validation:latest # Your Docker image
    container_name: events-app
    ports:
      - "8089:8089" # Exposes the application on port 8080
    depends_on:
      - nexus
      - sonarqube # Waits for SonarQube to start before starting the app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/eventsProject?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  nexus-data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local
